### ISSUE TITLE
InvalidArgumentError: slice index 0 of dimension 0 out of bounds RNN 

### ISSUE THREAD

**Issue by niranjan8129** [JHart96/keras_elmo_embedding_layer#6]
@JHart96 @Deep1994

Please help me to overcome this issue  below. Getting error at line no 3

I am using the below code in Tensorflow 2.0:

1) lstm_cell = tf.keras.layers.LSTMCell(units=128)
2) lstm_cell = tf.nn.RNNCellDropoutWrapper(lstm_cell,output_keep_prob=.5)
3) self._initial_state = lstm_cell.get_initial_state(128, tf.float32)

ValueError: slice index 0 of dimension 0 out of bounds. for strided_slice (op: StridedSlice) with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3]

**Comment by JHart96** [comment]
Hello,
Would you be able to post a working example of your code so that I can recreate the issue?
Thanks,
Jordan

**Comment by niranjan8129** [comment]
@JHart96  here you go 

!git clone https://github.com/niranjan8129/classification_tensorflow
!pip install tensorflow-gpu==2.0.0-beta1
from google.colab import drive
dirpath=drive.mount('/classification_tensorflow')

!chmod 777 classification_tensorflow
!python ./classification_tensorflow/train.py ./classification_tensorflow/data/train.csv.zip ./classification_tensorflow/training_config.json

**Comment by JHart96** [comment]
Thanks for that. I can't find where you're using this repository in your code, would you be able to tell me which file and which line you use this ELMo implementation in?

**Comment by niranjan8129** [comment]
I am extremely sorry  friend . Kindly delete the comments thread   i do not have any problem  on this model.
